### ISSUE TITLE
any attribute wilcards?

### ISSUE THREAD

**Issue by cigzigwon** [BlueM/XMLTransformer#5]
I don't see any usage for something like @* OR @name:* which wouldbe very handy for mass removal of unwanted attrs.

**Comment by BlueM** [comment]
There is no way to do this directly in XMLTransformer. But with version 1.1 (tagged a few minutes ago, which means it will be available via Composer shortly), the callback can take the arguments by reference – as usual, by prefixing the argument with an ampersand. (Exception: this won’t work with PHP 5.3.)

Example callback function:

```php
function callback($elementName, &$attributes, $elementType)
{
    $attributes = []; // <-- This will clear all attributes
    return [
        '@title' => 'You can still set attributes like this',
    ];
}
```

Likewise, any other kind of filtering or removal can be accomplished using plain PHP.

**Comment by cigzigwon** [comment]
sweet man ur awesome! this really works great for me and just started using
it.
